### PR TITLE
Add section on R-squared to Ch 3

### PR DESCRIPTION
**Pull request by staceyhancock**
Thought you might want to use some of this material, but feel free to ignore!

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for this suggestion. I'm happy to merge it with some minor changes: I moved it down to where we first introduce R-squared in the next section and made the annotated plot in R. Before I do though, I wasn't sure how you picked the variability around 85 to be the "numerator"?

I might also update the example to match the one used in that section of text but for now left it with possums.

**Comment by staceyhancock** [comment]
Variability around 85 was an arbitrarily chosen x-value. I thought maybe that would be more clear than abstractly talking about variability in y "when we know x", and would give the general idea of R-squared.

**Comment by mine-cetinkaya-rundel** [comment]
I see. In thinking through it, I'm worried it might be misleading, but let me know if you disagree with my reasoning below.

The bandwidth of the gray square affects the height (the difference between max and min y-values of the points that fall in that bandwidth), and the choice of the bandwidth here seems arbitrary.

I was also thinking about what happens if you have perfectly homoscedastic scatter on a line with an intercept but slope of 0. Correlation coefficient and the R-squared values would both be zero, but this ratio would tend to 1.

Let me know if you disagree with this reasoning. I'd love to include a diagram that solidifies this concept, but I also want to make sure it holds up under various conditions.

    library(broom)
    library(MASS)
    library(tidyverse)

    set.seed(1234)

    n = 1000
    r = 0

    mat <- mvrnorm(
      n = n, 
      mu = c(0, 0), 
      Sigma = matrix(c(1, r, r, 1), nrow = 2), 
      empirical = TRUE
      )


    df <- tibble(
      x = mat[,1],
      y = mat[,2]
    )

    # slope ~ 0
    m <- lm(y ~ x, data = df)
    tidy(m) %>% dplyr::select(term, estimate)
    #> # A tibble: 2 x 2
    #>   term         estimate
    #>   <chr>           <dbl>
    #> 1 (Intercept)  7.72e-17
    #> 2 x           -1.36e-15

    # r and R-squared ~ 0
    cor(df$x, df$y)
    #> [1] -1.388913e-15
    cor(df$x, df$y)^2
    #> [1] 1.929078e-30
    glance(m)$r.squared
    #> [1] 1.898575e-30

    # ratio as defined in the example ~ 1
    ggplot(df, aes(x = x, y = y)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      annotate("rect", 
               xmin = 0.5, xmax = 1.5, 
               ymin = min(df$y[df$x > 0.5 & df$x < 1.5]), 
               ymax = max(df$y[df$x > 0.5 & df$x < 1.5]), alpha = 0.2) +
      annotate("rect", 
               xmin = 2.5, xmax = 3.5, 
               ymin = min(df$y), 
               ymax = max(df$y), alpha = 0.2, fill = "green")
    #> `geom_smooth()` using formula 'y ~ x'



<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by staceyhancock** [comment]
I see your concern. The choice of bandwidth is indeed arbitrary, and if there were issues with non-constant variance, the analogy wouldn't work well.

Perhaps my explanation of the figure is the misleading part. My goal was to compare variability in y, ignoring x, (the range of y-values if we projected all the points onto the y-axis) to the variability around the regression line (the range of y-values for any given x-value). If we think of the green bar height as total variability in y (like the variance of y), then the height of the gray bar is the variability in y that is left-over after accounting for x (like the variance of the residuals). In the example with zero correlation, R-squared would be conceptualized as (height of green bar - height of gray bar)/(height of green bar), which would also be zero. I couldn't think of a better way of visualizing the _change_ in the variability - that difference between the green and gray bars.

**Comment by mine-cetinkaya-rundel** [comment]
I tried it with the other dataset (`elmhurst`) and it's pretty difficult to get the numbers to match, requires moving around the bands to hit the right number. And as you said, this is because we don't have perfect homoscedasticity with real data. 

r-squared-explanation-1

I think it either makes sense to do this with simulated data (which is not always clear for students) or to explain why numbers being "close enough" is good enough (which is also not an easy concept).

I'm leaning towards merging in your suggested changes in the section on R-squared but leaving out the figure for now. I'll open an issue with my code to produce the figure above so it's easy to come back to. I couldn't decide whether I'm overthinking it or it does require pausing and thinking a bit more. I definitely like the idea though, so I want to make sure we record it somewhere to see how we can demonstrate in a robust way.

**Comment by staceyhancock** [comment]
Sounds good. Thanks for considering my ideas!

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!!

**Pull request merged**
